name: Linting

on: [pull_request]
jobs:
  build_and_deploy_job:
    name: runner / textlint sarif
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: reviewdog/action-setup@v1
      - run: npm install
      - name: textlint sarif
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npx textlint -f @microsoft/eslint-formatter-sarif README.md | reviewdog -f=sarif -name="textlint" -reporter=github-check -level=info
