# name: Linting

# on: [pull_request]
# jobs:
#   build_and_deploy_job:
#     name: runner / textlint sarif
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v4
#       - uses: reviewdog/action-setup@v1
#       - run: npm install
#       - name: textlint sarif
#         env:
#           REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#         run: |
#           npx textlint -f @microsoft/eslint-formatter-sarif README.md | reviewdog -f=sarif -name="textlint" -reporter=github-check -level=info

name: reviewdog
on: [pull_request]
jobs:
  eslint:
    name: runner / eslint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
      - run: npm install
      - uses: reviewdog/action-eslint@v1
        with:
          reporter: github-check
          eslint_flags: "src/"
