name: Linting

on: [pull_request]
jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
    - name: Setup Node.js environment
      uses: actions/setup-node@v4.0.3
      with:
        node-version: 18
    - run: npm install @microsoft/eslint-formatter-sarif
    - uses: reviewdog/action-setup@v1
      with:
        reviewdog_version: latest # Optional. [latest,nightly,v.X.Y.Z]

    - name: review
      env:
        REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        reviewdog -reporter=github-pr-check
